### ISSUE TITLE
Database connection is lost after long server idle times

### ISSUE THREAD

**Issue by wesen1** [wesen1/wesenGemaMod#110]

**Comment by NadalB** [comment]
probably interactive_timeout or wait_timeout each has 8 hours inactivity by default in mysql and mariadb too. there is no way to disable but maybe solve the problem with some kind of timed function that make some kind of activity with the sql server.

**Comment by wesen1** [comment]
I added a periodic timer that should execute a query every 30 minutes.

https://github.com/wesen1/wesenGemaMod/blob/807caafaded589bf273e88f5bfa943636a328565/src/main.lua#L35-L41

But the error still happens, maybe the Timer's do not work while no player is connected.

**Comment by NadalB** [comment]
i tried and working fine with reduce the timeouts to 60sec and your timer to 30sec and also lost the connection if your timer had a higher value than the timeouts on sql. maybe u can try to set the timeouts to a higher value than 8hour like a week

**Comment by wesen1** [comment]
I found a bug with Timer's that is also probably the reason for the database connection loss:
1. Set up some periodic timers
2. Run a one-time timer (TYPE_ONCE)
3. When the one-time timer is queued or ran in the correct moment it will break one of the periodic timers (not sure why)

I could reproduce the problem with this test script:

```lua

local function log(_message)
  clientprint(-1, _message)
  logline(ACLOG_INFO, _message)
end

local Timer = require "AC-LuaServer.Core.Util.Timer"


Timer:new(
  Timer.TYPE_PERIODIC,
  1000,
  function()
    log("Timer #1")
  end
)

Timer:new(
  Timer.TYPE_PERIODIC,
  2000,
  function()
    log("Timer #2")
  end
)

function onPlayerSayText()
  log("Queuing one-time timer")
  Timer:new(
    Timer.TYPE_ONCE,
    2000,
    function()
      log("Running one-time timer")
    end
  )
end
```

Then if I use `/loop i 3 [ say $i ]` ingame, the first periodic timer will break and the one-time timer will be called 4 times instead of the expected 3.

Test Logs:

```
ac-lua-server_1  | 2021-01-26T20:52:10.306601305Z Demo recording started.
ac-lua-server_1  | 2021-01-26T20:52:10.306639612Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:10.306648997Z Timer #2
ac-lua-server_1  | 2021-01-26T20:52:11.329537681Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:12.310058869Z Timer #2
ac-lua-server_1  | 2021-01-26T20:52:12.332485802Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:13.335361573Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:13.536428389Z Queuing one-time timer
ac-lua-server_1  | 2021-01-26T20:52:13.536480697Z [172.22.0.1] unarmed says: '0'
ac-lua-server_1  | 2021-01-26T20:52:13.536852713Z Queuing one-time timer
ac-lua-server_1  | 2021-01-26T20:52:13.536881258Z [172.22.0.1] unarmed says: '1'
ac-lua-server_1  | 2021-01-26T20:52:13.538725570Z Queuing one-time timer
ac-lua-server_1  | 2021-01-26T20:52:13.538777087Z [172.22.0.1] unarmed says: '2'
ac-lua-server_1  | 2021-01-26T20:52:14.310788492Z Timer #2
ac-lua-server_1  | 2021-01-26T20:52:14.336974546Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:15.336748828Z Timer #1
ac-lua-server_1  | 2021-01-26T20:52:15.535756191Z Running one-time timer
ac-lua-server_1  | 2021-01-26T20:52:15.536361147Z Running one-time timer
ac-lua-server_1  | 2021-01-26T20:52:15.536831397Z Running one-time timer
ac-lua-server_1  | 2021-01-26T20:52:15.541683201Z Running one-time timer
ac-lua-server_1  | 2021-01-26T20:52:16.311564707Z Timer #2
ac-lua-server_1  | 2021-01-26T20:52:18.313901207Z Timer #2
ac-lua-server_1  | 2021-01-26T20:52:20.317945993Z Timer #2
```

**Comment by wesen1** [comment]
Ok, the problem seems to be in https://github.com/wesen1/AC-Lua/blob/2fc556a59048cd2ee7008d6d25f3a2491aeb8514/src/lua_tmr_library.cpp#L221.

I just tried it, the one-time timers sometimes get IDs that are already in use, and sometimes the ID's are negative numbers.

**Comment by wesen1** [comment]
Found the bug:

The code assumes that the list of timers is sorted by ID which it is not.
It works like this:
* Get current timer ID
* Calculate previous and next number relative to current timer ID
* Check if the previous or next number are used in all timers **following** the current timer (here is the problem, the ones preceding the current timer must be considered too)
* If one of the IDs is not used by the following timers it will be returned as vacant ID
* Fallback is 0 when there are no timers

So the wrong ID's happen like this:

* First timer:
  - Existing timers: []
  - Gets 0
* Second timer:
  - Existing timers: [0]
  - Checks -1 and 1, prefers next, so it gets 1
* Third timer:
  - Existing timers: [0, 1]
  - Checks -1 and 1, next is already reserved, so it gets -1
* Fourth timer:
  - Existing timers: [0, 1, -1]
  - Checks -1 and 1, both used, moves to next number
  - Checks 0 and 2: The next ID's (-1) are neither 0 nor 2, so it gets 0

Made a fix and will update AC-Lua tomorrow, then we can check if the database connection losses still happen.
