### ISSUE TITLE
ScoreAttempt enchantment

### ISSUE THREAD

**Issue by NadalB** [wesen1/wesenGemaMod#92]
When a player score and there was an exist score and the difference between the new and older score shown in the new score's output.

Sorry for the bad english.

**Comment by wesen1** [comment]
Hi,

thanks for your interest in this project.

I planned to add this feature and now the first version is finished (See Pull Request).
It will be merged and added to the running gema servers later today.

No problem with the description, I perfectly understand what you mean.
