### ISSUE TITLE
!status command

### ISSUE THREAD

**Issue by NadalB** [wesen1/wesenGemaMod#98]
Usage - !status name and without the arg return self status

Outputs:

- Rank
- How many best record the player own
- Own records
- Uploaded maps
- Geolocation if added in the future
- if have admin under the name. this require limited and full admins

its similar to the !whois command but this one for the non admin players

**Comment by wesen1** [comment]
Sorry, I saw this feature request but I am working on something else currently: Showing only the best score per player name in !maptop and !gtop to avoid `<name>#id` in the lists.

I can see something like this command added in the future, maybe renamed to !playerinfo or !playerstatus, !status is too generic
